"""Add merge_enabled column to replication_task table

Revision ID: 1aaf949f254e
Revises: 
Create Date: 2025-03-21 21:44:47.351621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaf949f254e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('dataset', sa.String(length=100), nullable=True),
    sa.Column('credentials_json', sa.Text(), nullable=True),
    sa.Column('database', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_schema', sa.String(length=100), nullable=True),
    sa.Column('endpoint_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replication_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('cdc_type', sa.String(length=20), nullable=True),
    sa.Column('cdc_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('last_position', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('initial_load', sa.Boolean(), nullable=True),
    sa.Column('create_tables', sa.Boolean(), nullable=True),
    sa.Column('replication_mode', sa.String(length=20), nullable=True),
    sa.Column('merge_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['endpoint.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['endpoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replication_task')
    op.drop_table('endpoint')
    # ### end Alembic commands ###
