"""Add last_updated to ReplicationTask

Revision ID: 58c36146ff3b
Revises: 94abff739302
Create Date: 2025-04-06 18:16:57.896771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c36146ff3b'
down_revision = '94abff739302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replication_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replication_task', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
