"""Add table selection and load options to tasks

Revision ID: 80f1c858d253
Revises: 051c0bf4ea09
Create Date: 2025-03-05 22:55:14.968449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f1c858d253'
down_revision = '051c0bf4ea09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replication_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_load', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_tables', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('replication_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replication_task', schema=None) as batch_op:
        batch_op.drop_column('replication_mode')
        batch_op.drop_column('create_tables')
        batch_op.drop_column('initial_load')

    # ### end Alembic commands ###
